version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install build-essential cmake libftdi1-dev
      - run: mkdir build
      - run:
          working_directory: build
          command: cmake ../
      - run:
          working_directory: build
          command: make UnitTest
      - run:
          working_directory: build
          command: make package
      - run:
          working_directory: build
          command: sudo dpkg -i `cat deb-package-name`
      - run:
          working_directory: build
          command: txvc -h

workflows:
 version: 2
 regular:
   jobs:
     - build-and-test

