version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run:
          command: sudo apt install build-essential cmake libftdi1-dev
      - run:
          command: mkdir build
      - run:
          working_directory: build
          command: cmake ../
      - run:
          working_directory: build
          command: make all
      - run:
          working_directory: build
          command: make UnitTest

workflows:
 version: 2
 regular:
   jobs:
     - build-and-test

