version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - run:
          name: Build and package
          working_directory: build
          command: |
            cmake ../
            make UnitTest
            make package
      - run:
          name: Install and verify DEB package
          working_directory: build
          command: |
            sudo dpkg -i $(cat deb-package-name)
            txvc -h
      - run:
          name: Prepare artifacts
          working_directory: build
          command: |
            mkdir -p deb
            cp $(cat deb-package-name) deb/
      - store_artifacts:
          path: build/deb

workflows:
  version: 2
  regular:
    jobs:
      - build-and-test
