version: 2.1

jobs:
  build-and-test:
    docker:
      - image: ghcr.io/cimg/cpp:2024.05  # Pre-packaged with GCC, CMake, Ninja, and Make
    steps:
      - checkout
      - run:
          name: Build and package
          working_directory: build
          command: |
            cmake -G Ninja ../
            ninja UnitTest
            ninja package
      - run:
          name: Install and verify DEB package
          working_directory: build
          command: |
            sudo dpkg -i $(cat deb-package-name)
            txvc -h
      - run:
          name: Prepare artifacts
          working_directory: build
          command: |
            mkdir -p deb
            cp $(cat deb-package-name) deb/
      - store_artifacts:
          path: build/deb

workflows:
  version: 2
  regular:
    jobs:
      - build-and-test
