#!/usr/bin/env sh

if command -v udevadm &> /dev/null
then
    echo Applying txvc udev rules ...
    udevadm control --reload
else
    echo Udev rules were not applied. Install udevadm and reload rules manually.
fi

